#!/bin/bash
set -xeuo pipefail

# ---------------------------------------------------------------------
# Build best stable (for usage with Castle Game Engine) version of Lazarus.
# Uses the best stable FPC version built by castle-fpc repo
# ( https://github.com/castle-engine/castle-fpc ).
#
# This is very similar in organization and purpose to the castle-fpc/build_fpc
# script, see there for a lot of comments:
# https://github.com/castle-engine/castle-fpc/blob/master/build_fpc
#
# Just like build_fpc, this expects 2 command-line parameters,
# OS and CPU, in the FPC naming conventions.
# These are target OS and CPU to build for.... and source OS and CPU too,
# we assume that they are the same, which allows us to test the freshly
# build Lazarus on the same machine we build it on.
#
# Made to be self-containing, so this doesn't modify system-wide files
# or $HOME/.fpc.cfg etc.
# ---------------------------------------------------------------------

# read params from command line
OS=$1
CPU=$2
shift 2

source castle-fpc/build_utilities

# ---------------------------------------------------------------------
# bash functions, do_xxx, to be executed in order to perform the script logic.

# Determine variables used through the rest of the script.
do_setup_environment ()
{
  # Lazarus branch or tag.
  # See for posibilities:
  # https://gitlab.com/freepascal.org/lazarus/lazarus/-/tags
  # https://gitlab.com/freepascal.org/lazarus/lazarus/-/branches
  #LAZARUS_BRANCHTAG='main' # use this for very latest commit
  LAZARUS_BRANCHTAG='lazarus_4_4'

  ZIP_NAME="lazarus-${OS}-${CPU}.zip"

  if [ "${IS_WINDOWS}" = "true" ]; then
    EXE_EXT='.exe'
  else
    EXE_EXT=''
  fi

  echo "Variables calculated:"
  echo "  ZIP_NAME (we will make this file): ${ZIP_NAME}"
  echo "  EXE_EXT: ${EXE_EXT}"
  echo
  echo "  OS and CPU (source and target):"
  echo "  OS: ${OS}"
  echo "  CPU: ${CPU}"
}

# cleanup leftover files from previous runs
do_cleanup ()
{
  rm -Rf lazarus/ fpc/ fpc-build-resources/ fpc-config/ \
    fpc-*.zip lazarus-*.zip
}

# get Lazarus sources to lazarus/
do_lazarus_sources_get ()
{
  git clone https://gitlab.com/freepascal.org/lazarus/lazarus.git \
    -c advice.detachedHead=false \
    --depth 1 --single-branch --branch "${LAZARUS_BRANCHTAG}" lazarus
  rm -Rf lazarus/.git # smaller zip size and disk space, and we no longer need it
}

# Get FPC build from castle-fpc
do_fpc_get ()
{
  # Using --progress=... below because default wget progress (default or --progress=dot) causes hard to read output in GHA logs.
  wget --progress=bar:force:noscroll \
    https://github.com/castle-engine/castle-fpc/releases/download/snapshot/fpc-"${OS}"-"${CPU}".zip
  # Use -q for more readable output in logs.
  unzip -q "fpc-${OS}-${CPU}.zip"
  rm -f "fpc-${OS}-${CPU}.zip" # no longer needed, save disk space, important for GHA on GH-hosted runners
}

# calculate $FPC_OPTS which are used to call FPC .
do_calculate_fpc_opts ()
{
  utils_calculate_fpc_opts

  # Add -Fu to standard units, following castle-fpc/README.md
  FPC_OPTS="-Fu${WORKSPACE_ROOT}/fpc/units/${CPU}-${OS}/* ${FPC_OPTS}"
}

do_lazarus_build ()
{
  if [ "${IS_WINDOWS}" = "true" ]; then
    utils_download_and_setup_fpc_build_resources
  fi

  # Unused. For now, we just package source + build together
  # make clean all install INSTALL_PREFIX="${LAZARUS_INSTALL}" -C lazarus/

  make clean all -C lazarus/ \
    FPC="${WORKSPACE_ROOT}/fpc/bin/fpc" \
    OPT="${FPC_OPTS}"

  if [ "${IS_WINDOWS}" = "true" ]; then
    export PATH="$RESTORE_PATH"
  fi
}

# pack to zip.
do_pack_zip ()
{
  if which 7z > /dev/null; then
    # Use 7z if available.
    #
    # This is preinstalled on GH hosted Windows, in contrast to zip.
    # ( We could alternatively install zip, e.g. using Chocolatey,
    # or use PowerShell
    # "run: Compress-Archive -Path folder/ -Destination new.zip"
    # see https://stackoverflow.com/questions/74939762/create-zip-file-of-github-reporitory-using-a-workflow-which-runs-on-windows-lat )
    #
    # It also seems to be actively maintained and very powerful,
    # so let's use it.
    #
    # We use -snl to avoid warnings (and exit with non-zero status)
    # because of invalid symlink "lazarus/components/chmhelp/lhelp/lhelp.app/Contents/MacOS/lhelp" .

    7z a ${ZIP_NAME} lazarus/ -snl
  else
    zip -r ${ZIP_NAME} lazarus/
  fi
}

# Test that build Lazarus can compile a simple project.
do_test_program ()
{
  # We need to pass $FPC_OPTS to fpc that is executed by lazbuild.
  #
  # lazbuild --opt doesn't enable us to pass options to all FPC invocations,
  # also when it builds lpk that are used by the main project.
  # So we need to just create config file.
  mkdir -p fpc-config/
  for OPT in ${FPC_OPTS}; do
    echo "${OPT}" >> fpc-config/fpc.cfg
  done
  # FPC will look there for fpc.cfg, following https://wiki.freepascal.org/Configuration_file
  export PPC_CONFIG_PATH="${WORKSPACE_ROOT}/fpc-config"

  lazarus/lazbuild \
    --lazarusdir="${WORKSPACE_ROOT}/lazarus" \
    --compiler="${WORKSPACE_ROOT}/fpc/bin/fpc${EXE_EXT}" \
    test_project/test_project.lpi

  if [ "${OS}" = 'linux' ]; then
    echo 'Aborting running test_project, as it cannot be done with a display (e.g. on CI/CD).'
    return
  fi

  local TEST_PROGRAM_OUTPUT="`./test_project/test_project`"
  if [ "$IS_WINDOWS" = 'true' ]; then
    # remove \r at the end, following https://superuser.com/questions/489180/remove-r-from-echoing-out-in-bash-script
    TEST_PROGRAM_OUTPUT="${TEST_PROGRAM_OUTPUT%%[[:cntrl:]]}"
  fi

  if [ "${TEST_PROGRAM_OUTPUT}" != "Hello World!" ]; then
    echo "Test program failed to execute correctly. Output: $TEST_PROGRAM_OUTPUT"
    exit 1
  fi
}

# ---------------------------------------------------------------------
# main: execute bash functions in order

utils_setup_environment
do_setup_environment
do_cleanup
do_lazarus_sources_get
do_fpc_get
do_calculate_fpc_opts
do_lazarus_build
do_pack_zip
do_test_program